name: Use Global Python Checks

on:
  push:
    branches: ["main", "develop", "dev", "feature/*"]
  pull_request:

permissions:
  contents: read
  issues: write   # ✅ pass issue permissions down to reusable workflow

jobs:
  run-global:
    uses: sanjaydevelopment/org-ci-workflows/.github/workflows/python-checks.yml@main
    secrets: inherit
