name: Use Global Python Checks

on:
  push:
    branches: ["main", "develop", "dev", "feature/*"]
  pull_request:

jobs:
  run-global:
    uses: sanjaydevelopment/.github/.github/workflows/python-checks.yml@main
